### ISSUE TITLE
Exception when launching the extension in debug mode

### ISSUE THREAD

**Issue by bensonnw** [OpenLiberty/liberty-dev-vscode-ext#49]
stack trace: Error: Cannot find module 'gradle-to-js/lib/parser'
Require stack:
- c:\git\devEx\liberty-dev-vscode-ext\out\utils\libertyProject.js
- c:\git\devEx\liberty-dev-vscode-ext\out\extension.js
- c:\sfs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\sfs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\sfs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.<anonymous> (internal/modules/cjs/loader.js:531:27)
	at Function.<anonymous> (c:\sfs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:837:268)
	at Function.<anonymous> (c:\sfs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:807:106)
	at Function._load (c:\sfs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:550)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at n (c:\sfs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at ProjectProvider.<anonymous> (c:\git\devEx\liberty-dev-vscode-ext\out\utils\libertyProject.js:89:26)
	at Generator.next (<anonymous>)
	at c:\git\devEx\liberty-dev-vscode-ext\out\utils\libertyProject.js:7:71
	at new Promise (<anonymous>)
	at c:\git\devEx\liberty-dev-vscode-ext\out\utils\libertyProject.js:3:12
	at ProjectProvider.findValidGradleBuildFiles (c:\git\devEx\liberty-dev-vscode-ext\out\utils\libertyProject.js:84:16)

**Comment by bensonnw** [comment]
`gradle-to-js` is newly added dependency which is missing locally, after installing it, the exception is gone, closing it.
